# Configuration for librarian-puppet. For example:
 
forge "http://forge.puppetlabs.com"
 
mod "thomasvandoren/redis"
mod "puppetlabs/mongodb"
mod "puppetlabs/nodejs"

#mod "jenkins",
#  :git => "git://github.com/pgr0ss/puppet-jenkins.git"                 
  
mod "jenkins",
  :git => "git://github.com/jenkinsci/puppet-jenkins.git"
mod "apt",
  :git => "git://github.com/puppetlabs/puppetlabs-apt.git"
mod "stdlib",
  :git => "git://github.com/puppetlabs/puppetlabs-stdlib.git"  
